/**
 * LILLIE — Portfolio Export
 *
 * Deterministic export builders for the generated portfolio:
 *   - `json`     → the full PortfolioContent payload (machine-readable)
 *   - `html`     → a self-contained personal-website page with the theme
 *     applied inline (zero external assets — works offline, paste anywhere)
 *   - `markdown` → a README-style portfolio document
 *
 * All three consume the SAME PortfolioContent — no re-implementation of
 * the generators, no duplicated data shapes. HTML is built with a small
 * escaper so GitHub-supplied text (bio, descriptions) can never inject
 * markup into the generated site.
 */

import type { PortfolioContent } from "./types";
import type { PortfolioTheme } from "./themes";

// ═══════════════════════════════════════════════════════════════════
// Escaping
// ═══════════════════════════════════════════════════════════════════

/** Escapes text for safe inclusion in generated HTML. */
function escapeHtml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * URL scheme whitelist — the same rule as src/lib/sanitize-model.ts.
 * escapeHtml escapes markup but does NOT stop `javascript:` URLs in
 * href/src attributes, so URLs must be http(s) only.
 */
const SAFE_URL_RE = /^https?:\/\//i;

function safeUrl(value: string): string {
  const trimmed = value.trim();
  return SAFE_URL_RE.test(trimmed) ? trimmed : "";
}

// ═══════════════════════════════════════════════════════════════════
// Markdown
// ═══════════════════════════════════════════════════════════════════

export function buildPortfolioMarkdown(content: PortfolioContent): string {
  const { hero, stats, about, skills, featuredProjects, achievements, techStack } = content;
  const lines: string[] = [];

  lines.push(`# ${hero.name}`);
  lines.push("");
  if (hero.headline) lines.push(`> ${hero.headline}`);
  if (hero.bio) lines.push("");
  if (hero.bio) lines.push(hero.bio);
  lines.push("");
  lines.push(`- **Repositories:** ${stats.repos}`);
  lines.push(`- **Stars:** ${stats.stars}`);
  lines.push(`- **Forks:** ${stats.forks}`);
  lines.push(`- **Years on GitHub:** ${stats.years}`);
  if (hero.location) lines.push(`- **Location:** ${hero.location}`);
  if (hero.website) lines.push(`- **Website:** ${hero.website}`);
  lines.push("");

  lines.push("## About");
  lines.push("");
  about.paragraphs.forEach((p) => lines.push(p, ""));
  if (about.highlights.length > 0) {
    lines.push("**Highlights:** " + about.highlights.join(", "));
    lines.push("");
  }

  if (skills.length > 0) {
    lines.push("## Skills");
    lines.push("");
    lines.push(skills.map((s) => s.name).join(", "));
    lines.push("");
  }

  if (featuredProjects.length > 0) {
    lines.push("## Featured Projects");
    lines.push("");
    for (const p of featuredProjects) {
      lines.push(`### ${p.name}`);
      lines.push("");
      lines.push(p.description || "No description yet.");
      lines.push("");
      lines.push(
        `- ${p.stars} stars · ${p.forks} forks` +
          (p.language ? ` · ${p.language}` : "") +
          (p.topics.length > 0 ? ` · ${p.topics.slice(0, 4).join(", ")}` : "")
      );
      lines.push("");
      lines.push(p.url);
      lines.push("");
    }
  }

  const earned = achievements.filter((a) => a.earned);
  if (earned.length > 0) {
    lines.push("## Achievements");
    lines.push("");
    earned.forEach((a) => lines.push(`- ${a.icon} **${a.title}** — ${a.description}`));
    lines.push("");
  }

  if (techStack.length > 0) {
    lines.push("## Tech Stack");
    lines.push("");
    lines.push(
      techStack
        .map((t) => `${t.name} (${t.percent}%)`)
        .join(" · ")
    );
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`_Generated by LILLIE — theme: ${content.themeId}_`);
  lines.push("");
  return lines.join("\n");
}

// ═══════════════════════════════════════════════════════════════════
// HTML (self-contained personal website)
// ═══════════════════════════════════════════════════════════════════

function themeCss(theme: PortfolioTheme): string {
  const { colors, font, layout, radius, dark } = theme;
  const cardLayout =
    layout === "cards"
      ? "grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));"
      : layout === "split"
        ? "grid-template-columns: 1fr 2fr;"
        : "grid-template-columns: 1fr;";

  return `
:root {
  --bg: ${colors.bg};
  --surface: ${colors.surface};
  --text: ${colors.text};
  --muted: ${colors.muted};
  --accent: ${colors.accent};
  --border: ${colors.border};
  --font: ${font};
  --radius: ${radius};
  color-scheme: ${dark ? "dark" : "light"};
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body {
  background: var(--bg);
  color: var(--text);
  font-family: var(--font);
  line-height: 1.6;
  padding: 2rem 1rem;
}
.wrap { max-width: 960px; margin: 0 auto; }
header.hero {
  display: flex; gap: 1.5rem; align-items: center;
  flex-wrap: wrap; margin-bottom: 2rem;
}
.avatar {
  width: 96px; height: 96px; border-radius: 50%;
  background: var(--surface); border: 2px solid var(--border);
  display: flex; align-items: center; justify-content: center;
  font-size: 2.5rem; color: var(--accent); overflow: hidden;
}
.avatar img { width: 100%; height: 100%; object-fit: cover; }
h1 { font-size: 2rem; line-height: 1.2; }
.headline { color: var(--accent); font-weight: 600; margin: .25rem 0 .5rem; }
.bio { color: var(--muted); }
.meta { display: flex; gap: 1rem; flex-wrap: wrap; margin-top: .5rem; color: var(--muted); font-size: .9rem; }
section { margin: 2rem 0; }
h2 {
  font-size: 1.25rem; margin-bottom: 1rem;
  padding-bottom: .5rem; border-bottom: 2px solid var(--accent);
  display: inline-block;
}
.grid { display: grid; ${cardLayout} gap: 1rem; }
.card {
  background: var(--surface); border: 1px solid var(--border);
  border-radius: var(--radius); padding: 1rem;
}
.card h3 { font-size: 1rem; margin-bottom: .25rem; }
.card .desc { color: var(--muted); font-size: .9rem; }
.card .meta-line { color: var(--accent); font-size: .8rem; margin-top: .5rem; }
.skill-tag {
  display: inline-block; background: var(--surface);
  border: 1px solid var(--border); border-radius: 999px;
  padding: .25rem .75rem; margin: .25rem; font-size: .85rem;
}
.stack { display: flex; flex-wrap: wrap; gap: .5rem; }
.ach { display: flex; gap: .75rem; align-items: flex-start; margin: .5rem 0; }
.ach .icon { font-size: 1.25rem; }
.ach .earned { color: var(--muted); font-size: .85rem; }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
footer { margin-top: 3rem; color: var(--muted); font-size: .85rem; border-top: 1px solid var(--border); padding-top: 1rem; }
`.trim();
}

function projectCardHtml(p: PortfolioContent["featuredProjects"][number]): string {
  const url = safeUrl(p.url);
  return `
<article class="card">
  <h3><a href="${escapeHtml(url)}" rel="noopener noreferrer">${escapeHtml(p.name)}</a></h3>
  <p class="desc">${escapeHtml(p.description || "No description yet.")}</p>
  <p class="meta-line">★ ${p.stars} · ⑂ ${p.forks}${p.language ? ` · ${escapeHtml(p.language)}` : ""}</p>
</article>`;
}

export function buildPortfolioHtml(
  content: PortfolioContent,
  theme: PortfolioTheme
): string {
  const { hero, stats, about, skills, featuredProjects, achievements, techStack } = content;
  const earned = achievements.filter((a) => a.earned);

  const avatarSrc = safeUrl(hero.avatarUrl ?? "");
  const avatar = avatarSrc
    ? `<img src="${escapeHtml(avatarSrc)}" alt="${escapeHtml(hero.name)} avatar" />`
    : escapeHtml(hero.name.charAt(0).toUpperCase());

  const metaParts: string[] = [
    `${stats.repos} repositories`,
    `${stats.stars} stars`,
    `${stats.forks} forks`,
    `${stats.years} years on GitHub`,
  ];
  if (hero.location) metaParts.push(escapeHtml(hero.location));
  const website = safeUrl(hero.website ?? "");
  if (website) metaParts.push(`<a href="${escapeHtml(website)}" rel="noopener noreferrer">${escapeHtml(website)}</a>`);

  const projectCards = featuredProjects.map(projectCardHtml).join("\n");
  const skillTags = skills.map((s) => `<span class="skill-tag">${escapeHtml(s.name)}</span>`).join("\n");
  const stackItems = techStack
    .map((t) => `<span class="skill-tag">${escapeHtml(t.name)} (${t.percent}%)</span>`)
    .join("\n");
  const achievementItems = earned
    .map(
      (a) =>
        `<div class="ach"><span class="icon">${a.icon}</span><div><strong>${escapeHtml(a.title)}</strong><div class="earned">${escapeHtml(a.description)}</div></div></div>`
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${escapeHtml(hero.name)} — Portfolio</title>
<style>${themeCss(theme)}</style>
</head>
<body>
<div class="wrap">
  <header class="hero">
    <div class="avatar">${avatar}</div>
    <div>
      <h1>${escapeHtml(hero.name)}</h1>
      ${hero.headline ? `<p class="headline">${escapeHtml(hero.headline)}</p>` : ""}
      ${hero.bio ? `<p class="bio">${escapeHtml(hero.bio)}</p>` : ""}
      <p class="meta">${metaParts.join(" · ")}</p>
    </div>
  </header>

  <section>
    <h2>About</h2>
    ${about.paragraphs.map((p) => `<p style="margin-bottom:.75rem">${escapeHtml(p)}</p>`).join("\n")}
  </section>

  ${skills.length > 0 ? `
  <section>
    <h2>Skills</h2>
    <div class="stack">${skillTags}</div>
  </section>` : ""}

  ${featuredProjects.length > 0 ? `
  <section>
    <h2>Featured Projects</h2>
    <div class="grid">${projectCards}</div>
  </section>` : ""}

  ${earned.length > 0 ? `
  <section>
    <h2>Achievements</h2>
    ${achievementItems}
  </section>` : ""}

  ${techStack.length > 0 ? `
  <section>
    <h2>Tech Stack</h2>
    <div class="stack">${stackItems}</div>
  </section>` : ""}

  <footer>
    Generated by LILLIE · theme <strong>${escapeHtml(theme.name)}</strong>
  </footer>
</div>
</body>
</html>`;
}

// ═══════════════════════════════════════════════════════════════════
// JSON
// ═══════════════════════════════════════════════════════════════════

/** Pretty-printed JSON export of the full portfolio payload. */
export function buildPortfolioJson(content: PortfolioContent): string {
  return JSON.stringify(content, null, 2);
}
