import { notFound } from "next/navigation";
import Link from "next/link";
import { cache } from "react";
import { headers } from "next/headers";
import { prisma } from "@/lib/db";
import { validateLocale, validateTemplate } from "@/lib/validate";
import { trackResumeView, hashVisitor } from "@/lib/analytics/events";
import { CvPreview } from "@/cv";
import type { CvModel } from "@/cv";
import type { Metadata } from "next";

/**
 * Public resume page — /r/:token
 *
 * Renders a profile's snapshotted CV for anyone with the link. No session
 * required. The snapshot (shareModel) was stored when the owner enabled
 * sharing, so this page never touches GitHub or the owner's session.
 *
 * If the token is unknown or sharing was disabled, we render a 404 so the
 * link cannot be probed (no difference between "never shared" and
 * "disabled").
 */
export const dynamic = "force-dynamic";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ token: string }>;
}): Promise<Metadata> {
  const { token } = await params;
  const profile = await findSharedProfile(token);
  if (!profile || !profile.shareModel) {
    return { title: "Resume not found — LILLIE" };
  }
  const model = profile.shareModel as unknown as CvModel;
  return {
    title: `${model.header.name} — Resume`,
    description: model.header.bio || `Resume of ${model.header.name}`,
  };
}

export default async function PublicResumePage({
  params,
}: {
  params: Promise<{ token: string }>;
}) {
  const { token } = await params;
  const profile = await findSharedProfile(token);

  if (!profile || !profile.shareModel) {
    notFound();
  }

  const model = profile.shareModel as unknown as CvModel;
  const locale = validateLocale(profile.locale) ?? "en";
  const template = validateTemplate(profile.template) ?? "classic_professional";

  // ── Record the public view (fire-and-forget, never fatal) ──────
  // Uses a salted IP hash — never the raw IP — so unique-visitor
  // estimation is privacy-safe. Analytics must not block the page.
  try {
    const headerStore = await headers();
    const forwarded = headerStore.get("x-forwarded-for");
    const ip = forwarded ? forwarded.split(",")[0].trim() : null;
    const referrer = headerStore.get("referer");
    void trackResumeView({
      userId: profile.userId,
      profileId: profile.id,
      visitorHash: hashVisitor(ip),
      referrer: referrer || null,
    });
  } catch (err) {
    console.error("Analytics: resume view skipped:", err);
  }

  return (
    <main className="min-h-screen bg-[#e8e5df] py-6 sm:py-10 px-2 sm:px-4">
      <div className="max-w-[820px] mx-auto">
        <div className="flex items-center justify-between mb-4 px-1">
          <span className="text-xs text-neutral-500">
            Shared with LILLIE
          </span>
          <Link
            href="/"
            className="text-xs text-neutral-500 hover:text-neutral-800 transition-colors underline underline-offset-2"
          >
            Create your own →
          </Link>
        </div>

        <div className="rounded-lg overflow-hidden shadow-2xl shadow-black/20 bg-white">
          <CvPreview
            model={model}
            templateId={template}
            locale={locale}
          />
        </div>

        <p className="text-center text-[11px] text-neutral-400 mt-4">
          Generated by LILLIE — turn your GitHub into a CV in 30 seconds.
        </p>
      </div>
    </main>
  );
}

/**
 * Looks up a profile by its unguessable share token and returns it only
 * when sharing is currently enabled.
 */
/**
 * Cached per-request lookup so generateMetadata and the page render share
 * a single database read for the same token.
 */
const findSharedProfile = cache(async (token: string) => {
  if (!token || !/^[A-Za-z0-9_-]{16,}$/.test(token)) return null;
  try {
    const profile = await prisma.cvProfile.findUnique({
      where: { shareToken: token },
      select: {
        id: true,
        userId: true,
        shareModel: true,
        shareEnabled: true,
        locale: true,
        template: true,
      },
    });
    if (!profile || !profile.shareEnabled) return null;
    return profile;
  } catch (err) {
    console.error("Failed to load shared profile:", err);
    return null;
  }
});
